### ISSUE TITLE
Roadmap for this plugin to be listed in Grafana plugins

### ISSUE THREAD

**Issue by srinathganesh** [CorpGlory/grafana-multibar-graph-panel#13]
Currently I cannot find this plugin at https://grafana.com/plugins and I have to manually install this. Is there a roadmap of when will this be listed there?

**Comment by jonyrock** [comment]
@srinathganesh nice idea, I think to remove all functionality which is not connected with rendering bars first.

**Comment by jonyrock** [comment]
And make an ico

**Comment by liakjim** [comment]
> 
> 
> Currently I cannot find this plugin at https://grafana.com/plugins and I have to manually install this. Is there a roadmap of when will this be listed there?

Can you point me a way to install this plugin in a hassio working on virtualbox?
