### ISSUE TITLE
Timebased bar graph

### ISSUE THREAD

**Issue by jonyrock** [CorpGlory/grafana-multibar-graph-panel#14]
This is how rendering is now: 

![image](https://user-images.githubusercontent.com/1022757/46489209-7782f000-c80d-11e8-98c2-a69ebf17a741.png)

Time based bar graph, with bars side by side, showing future dates with weekly time intervals ie Monday of every week:

![image](https://user-images.githubusercontent.com/1022757/46489295-b1ec8d00-c80d-11e8-807c-f75d1ffd748c.png)

**Comment by rozetko** [comment]
How would it look like when zoomed in? For example, you zoom to just one day (1 Oct) and you get time beyond bars. Bars are not connected to time though. Only to date.

**Comment by nsayedqt** [comment]
when i zoom in to 1 Oct now, the bars spread all over. Instead can we still have it on Oct 1, just different times? or just one default time on Oct 1?
![image](https://user-images.githubusercontent.com/23022014/46491692-06bde280-c7d1-11e8-8867-89f9aebfa883.png)

**Comment by nsayedqt** [comment]
Any update on this?
