### ISSUE TITLE
Time labels shift

### ISSUE THREAD

**Issue by rozetko** [CorpGlory/grafana-multibar-graph-panel#22]
Currently, if you have data grouped by week (for example) - you have time along with time labels shifted (there is 10/16 after 10/8, although it should be 10/15 after 10/8)
Current behaviour:
![image](https://user-images.githubusercontent.com/1989898/46752042-e0aeab80-ccc4-11e8-9d73-d22b146bff9a.png)
Expected behaviour:
![image](https://user-images.githubusercontent.com/1989898/46752077-f6bc6c00-ccc4-11e8-8cb0-c3141efddcb2.png)
@nsayedqt, am I right? Is it the expected behaviour?

**Comment by nsayedqt** [comment]
Yes that is correct

Regards,
Nausheen Sayed
Product Owner, QTDashboard

________________________________

**Comment by nsayedqt** [comment]
Also when I hover over the bars, the dates displayed are wrong. The data is organized or pointing to 10/8, 10/15, 10/22 but both the axes and hovering shows wrong dates. I am using MYSQL data source.

**Comment by rozetko** [comment]
We're implementing it currently
Going to generate labels by groups amount (if there are not much of groups - every group would have a label, if there are too much groups - every nth of them would be skipped)
For example:
- groups here are big enough - we can put label under each of them
![image](https://user-images.githubusercontent.com/1989898/46813712-e5846580-cd7f-11e8-8ed5-0aa487448d4c.png)
- but groups here are too small - we would skip label under every 2nd one
![image](https://user-images.githubusercontent.com/1989898/46813695-dac9d080-cd7f-11e8-81fd-ceeb98b9d315.png)

**Comment by nsayedqt** [comment]
Assuming the groups will have option for weekly grouping? Will it also resolve the issue with dates upon hovering on the bars (currently it is not showing correct date)?

**Comment by rozetko** [comment]
Hey, @nsayedqt

Let me make it clear:
Grouping is based on datasource response. Plugin doesn't transform data. It is something datasource should handle. 

Suppose you have such dataset:
![image](https://user-images.githubusercontent.com/1989898/46821915-b5928d80-cd92-11e8-868f-013785974bb8.png)
It is displayed like this:
![image](https://user-images.githubusercontent.com/1989898/46821977-d955d380-cd92-11e8-99fb-db8edd4b9e3b.png)

Also, you can test it here: 
http://grafana5.corpglory.com/d/r7Zvhi1ik/multibar
User: guest
Password: tx8yM

I believe you got your data already grouped by MySQL, so that should work in your case.

P.S. Could you please create another issue for tooltips? It would be nice to have more info on it (i.e. tooltip screenshots)

**Comment by nsayedqt** [comment]
looks right in your environment, but i need to test in mine. Where can i download the latest code?

**Comment by nsayedqt** [comment]
ok lets try this again:
This is my query result:
![image](https://user-images.githubusercontent.com/23022014/46823561-1d75b380-cd54-11e8-8a1b-d95b5848a67a.png)

this is my graph - x axes ticks are not pointing to correct dates and when i hover over it shows wrong dates as well
![image](https://user-images.githubusercontent.com/23022014/46823619-45651700-cd54-11e8-98db-bdae95e82dea.png)

my data is grouped correctly, query is correct but display is wrong
I hope i am able to convey my issue

**Comment by rozetko** [comment]
I'll make a release in half an hour and let you know
About tooltip: seems like timezone problem. What timezone is set in your dashboard? Seems like UTC

**Comment by nsayedqt** [comment]
its default timezone which i guess is UTC

**Comment by rozetko** [comment]
@nsayedqt you can try new release now:
```bash
cd $GRAFANA_PATH/data/plugins/
wget https://github.com/CorpGlory/grafana-multibar-graph-panel/releases/download/0.1.2/grafana-multibar-graph-panel-0.1.2.tar.gz
tar -zxvf grafana-multibar-graph-panel-0.1.2.tar.gz
```
And restart Grafana after that

**Comment by nsayedqt** [comment]
@rozetko  thanks will do now

**Comment by nsayedqt** [comment]
@rozetko    i dont see any change:
![image](https://user-images.githubusercontent.com/23022014/46828094-f91fd400-cd5f-11e8-83a9-7582e6749f54.png)

 infact the date changes when i hover on the bars. See how for 16 Oct, it is showing 15th on one bar, then 16th, then 17th... very confusing. 
![image](https://user-images.githubusercontent.com/23022014/46828153-24a2be80-cd60-11e8-923b-0d2fc3f438f0.png)

![image](https://user-images.githubusercontent.com/23022014/46828182-34ba9e00-cd60-11e8-90d6-fd43e4bbd6dc.png)

**Comment by rozetko** [comment]
Did you restart Grafana server after updating plugin?
Seems like Grafana cached an old plugin version
Can you please try to clear cache? F12 (Chrome Dev Tools would be opened) -> Right click on refresh button -> Empty Cache and Hard Reload 
![image](https://user-images.githubusercontent.com/1989898/46828773-ae747b00-cda4-11e8-9f96-98dbe2b91690.png)

**Comment by nsayedqt** [comment]
![image](https://user-images.githubusercontent.com/23022014/46829147-9f6cd900-cd62-11e8-9e5d-497a340ab623.png)

**Comment by nsayedqt** [comment]
@rozetko 
Tried on a new server, where this plugin was never installed. The **x axes is still off** though the dates on hovering are correct
![image](https://user-images.githubusercontent.com/23022014/46829721-22dafa00-cd64-11e8-8a4c-5874a1c1945d.png)

**Comment by nsayedqt** [comment]
@rozetko  due you think the plugin (or the ticks) is responding differently for a MYSQL data source?

**Comment by rozetko** [comment]
@nsayedqt seems like this is the reason

**Comment by rozetko** [comment]
I'll try it with MySQL tomorrow and we'll see

**Comment by nsayedqt** [comment]
@rozetko you know whats more scary - when i zoom in, or set time to last 30 or 7 days - the axes becomes zero:
![image](https://user-images.githubusercontent.com/23022014/46829913-c62c0f00-cd64-11e8-83be-b3f70d28a17d.png)

![image](https://user-images.githubusercontent.com/23022014/46829931-d217d100-cd64-11e8-8d3f-d1d90a27940e.png)
I dont see that in ur environment

**Comment by rozetko** [comment]
About zeroes: did you have the same behaviour with previous versions?

**Comment by nsayedqt** [comment]
@rozetko sorry dont remember - i just saw it

**Comment by rozetko** [comment]
@nsayedqt no problem

**Comment by nsayedqt** [comment]
@rozetko any luck reproducing it with MYSQL today?

**Comment by jonyrock** [comment]
@nsayedqt we are working on this right now

**Comment by rozetko** [comment]
Hey, @nsayedqt! Tested with MySQL and got the same result
![image](https://user-images.githubusercontent.com/1989898/46886127-9a8f4e80-ce62-11e8-9998-ee7ede72e9e2.png)
Let's wait until you test it with the new 0.1.3 version
