### ISSUE TITLE
Wrong time in tooltip

### ISSUE THREAD

**Issue by rozetko** [CorpGlory/grafana-multibar-graph-panel#24]
This is my query result:
![image](https://user-images.githubusercontent.com/23022014/46823561-1d75b380-cd54-11e8-8a1b-d95b5848a67a.png)

this is my graph - x axes ticks are not pointing to correct dates and when i hover over it shows wrong dates as well
![image](https://user-images.githubusercontent.com/23022014/46823619-45651700-cd54-11e8-98db-bdae95e82dea.png)

my data is grouped correctly, query is correct but display is wrong
I hope i am able to convey my issue

by @nsayedqt
continues discussion from here: https://github.com/CorpGlory/grafana-multibar-graph-panel/issues/22#issuecomment-429054576

**Comment by rozetko** [comment]
@nsayedqt let's continue here
Can you please try to set "Local browser time"? Would tooltip show proper date then?

**Comment by nsayedqt** [comment]
@rozetko 
local browser time didnt work, but now i set it to UTC and is showing correct dates - YAY!!!
thank you!!
![image](https://user-images.githubusercontent.com/23022014/46825524-73008f00-cd59-11e8-886c-54c6d14dc7b1.png)

**Comment by rozetko** [comment]
OK, I can close it then, I guess
