### ISSUE TITLE
Date in UK format

### ISSUE THREAD

**Issue by nsayedqt** [CorpGlory/grafana-multibar-graph-panel#26]
@jonyrock    please can you implement the UK date format (%d%b ie 2 Nov)  for the x-axes on the Multibar graph panel?

**Comment by jonyrock** [comment]
@nsayedqt sure. I think we can do it in 24 hours.

**Comment by rozetko** [comment]
Hi, @nsayedqt! We've implemented this feature
You can download new version from releases:
https://github.com/CorpGlory/grafana-multibar-graph-panel/releases/download/0.2.3/grafana-multibar-graph-panel-0.2.3.tar.gz

Now you can use your own date format (like `%d %b` you mentioned) when checking "Custom Date-Time format" box
This is how it looks like now
![image](https://user-images.githubusercontent.com/1989898/47669650-65059780-dbbc-11e8-8df7-f0922b7a4849.png)
