### ISSUE TITLE
custom date time format not used after switching modes

### ISSUE THREAD

**Issue by sankerust** [CorpGlory/grafana-multibar-graph-panel#29]
Custom Date-Time format is not used after switching X-Axis modes.

Steps to reproduce:
- Use custom Date-Time format
- Switch X-Axis mode from `Time` to any other
- Swith X-Axis mode back to `Time`  

Currently works only after browser page refresh.

**Comment by rozetko** [comment]
Fixed via https://github.com/CorpGlory/grafana-multibar-graph-panel/commit/869b9928e447c644e13a238e0950455a2ca95abe
