### ISSUE TITLE
side by side option not visible with grafana 5.4.3

### ISSUE THREAD

**Issue by arnaudlemaignen** [CorpGlory/grafana-multibar-graph-panel#33]
multibar version 0.2.4
grafana version 5.4.3

I guess this brilliant panel is not compatible with 5.4.3 as the side by side option is not even displayed.
![image](https://user-images.githubusercontent.com/22667740/53570749-87f28900-3b67-11e9-8c3a-ecae22802bb8.png)

 is there any plans to support this grafana 5.4 version?

thanks

**Comment by rozetko** [comment]
Hey, @arnaudlemaignen 
You have only "Lines" mode enabled but "Side-by-side" option is available only in "Bars" mode
Please, let me know if it helps

**Comment by arnaudlemaignen** [comment]
Thank you that's working ! , I did try a few configuration and confirm it is working well up to my knowledge in 5.4.3
My apology for not trying bars obviously.
And now I am wondering how it could look like to display lines side by side :)

**Comment by rozetko** [comment]
Glad to help :)
