### ISSUE TITLE
Color Picker Broken

### ISSUE THREAD

**Issue by danschewy** [CorpGlory/grafana-multibar-graph-panel#36]
![image](https://user-images.githubusercontent.com/6502595/56919543-d8fefa80-6a8e-11e9-9c9d-2d1ac41a4aee.png)
Color picker broken in graph view and when selecting Color in Series Override

**Comment by jonyrock** [comment]
@danschewy thx, we will soon provide a solution for this one.

**Comment by jonyrock** [comment]
This PR fixes same issue in similar panel: https://github.com/hastic/hastic-grafana-app/pull/289
So we need make change same change here

**Comment by rozetko** [comment]
Hey, @danschewy 
Sorry for a long wait
We've fixed it in the latest `0.2.5` release: https://github.com/CorpGlory/grafana-multibar-graph-panel/releases/tag/0.2.5

**Comment by ramivis** [comment]
Color Picker yet broken
