### ISSUE TITLE
Plugin installation problem Grafana version 5.4.3

### ISSUE THREAD

**Issue by HugoPimentel** [CorpGlory/grafana-multibar-graph-panel#37]
Once installed the plugin when trying to create a graph does not show the panel

![image](https://user-images.githubusercontent.com/51035870/58375610-6ca3d980-7f1c-11e9-8a79-ba6595a7c63d.png)

What else I need to do?

**Comment by jonyrock** [comment]
Hey

do you have any error? If you are on chrome browser, you can to "Inspect mode" and see  javascript errors

**Comment by bhargavisabbisetty** [comment]
You need to place the cloned folder in /usr/local/var/lib/grafana/plugins and do npm install, npm run build. And restart grafana. Then you will be able to use the plugin. It is working for me.
