### ISSUE TITLE
Plugin seems to crash in Grafana version 6.7.2

### ISSUE THREAD

**Issue by davidfa94** [CorpGlory/grafana-multibar-graph-panel#50]
Plugin was working fine, but after we updated Grafana from version **v6.5.3** to **v6.7.2** it just crashed:

![image](https://user-images.githubusercontent.com/10919318/80371797-c6cabe80-8892-11ea-9414-85db0d3f4f30.png)

Going into the plugin configuration tab, it says the following:

![image](https://user-images.githubusercontent.com/10919318/80371746-b0246780-8892-11ea-8da3-c222c030f089.png)

I'm pretty positive that the update was the reason why it crashed. Maybe you'd like to have a look in that case?

Regards

**Comment by jonyrock** [comment]
@davidfa94 would you support us on patreon with just few bucks to validate that somebody really need this issue to be fixed?:)

**Comment by davidfa94** [comment]
Well, everyone using this plugin will need it to at least compile once they update Grafana to the latest version

**Comment by jonyrock** [comment]
Thank you @davidfa94 ! Did you get thought the problem?
I case anybody want to support us: https://www.patreon.com/corpglory

**Comment by davidfa94** [comment]
I have to apologize because I've opened this issue and #49 in the wrong repository.

The problems are happening with a webpack done by using your [grafana-graph-panel](https://github.com/CorpGlory/grafana-graph-panel). There was some confusion on the origin of these problems.

I will close these issues so that they don't create any more confusion. Thanks for your time.
