### ISSUE TITLE
Y axis unit always set to date with Grafana 7.0.0-beta3

### ISSUE THREAD

**Issue by fpbrault** [CorpGlory/grafana-multibar-graph-panel#51]
Using [Grafana 7.0.0-beta3](https://community.grafana.com/t/release-notes-v7-0-x/29381), it appears that the Y axis unit type cannot be set correctly for multibar-graph-panel. No other custom or default visualizations appear to be affected by this issue.

![image](https://user-images.githubusercontent.com/1728218/81980899-75922d00-95fd-11ea-9a5e-da2f426956e5.png)

While you can select a unit type, it does not actually change the type used for the Y axis

![image](https://user-images.githubusercontent.com/1728218/81980952-8e9ade00-95fd-11ea-91dc-68781c0cffeb.png)

**Comment by jonyrock** [comment]
@fpbrault thank you for the report, but I have no idea when we will find time to fix it....

**Comment by jonyrock** [comment]
the only I can say, that if this functionality be implemented "for free", then it will be there: https://github.com/chartwerk/bar-chart/issues/6

**Comment by dbouchierarcad** [comment]
I have the same problem, 
I haven't updated grafana, I'm waiting for the fix thanks

**Comment by jonyrock** [comment]
@dbouchierarcad I feel your pain, let me think what we can do here.

**Comment by samindaroshan** [comment]
I have the same the problem. I would appreciate if you can fix this.

**Comment by jonyrock** [comment]
This is fixed. The new version available on master. Hope you will value our contribution here: https://www.patreon.com/corpglory  I strongly recommend to try https://github.com/chartwerk/grafana-chartwerk-panel , functionality there is limited, but this project actively supported.
