### ISSUE TITLE
Error when install and build

### ISSUE THREAD

**Issue by deepminimal** [CorpGlory/grafana-multibar-graph-panel#6]
Hello! When i build i have  error:

```
ERROR in ./module.ts
(301,27): error TS2339: Property 'yaxis' does not exist on type '{ alias: {}; }'.

ERROR in ./graph.ts
(491,29): error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in ./graph.ts
(495,17): error TS2554: Expected 1 arguments, but got 2.
```

And when i install:

```
warning @types/moment@2.13.0: This is a stub types definition for Moment (https://github.com/moment/moment). Moment provides its own type definitions, so you don't need @types/moment installed!
warning @types/perfect-scrollbar@1.3.0: This is a stub types definition for perfect-scrollbar (https://github.com/noraesae/perfect-scrollbar). perfect-scrollbar provides its own type definitions, so you don't need @types/perfect-scrollbar installed!
```

I see plugin, he work. But after reload page:

![image](https://user-images.githubusercontent.com/18044597/38088894-353959dc-3366-11e8-9607-21560c82334d.png)

```
node -v
v9.8.0

npm -v
5.8.0

grafana-cli -v
Grafana cli version 4.6.3

Centos 7.
```

**Comment by jonyrock** [comment]
@deepminimal have you tried to use plugin from `dist`? I just want to know if it works from `dist`.
It's not about your will to use it from source.

**Comment by rozetko** [comment]
Hi @deepminimal! According to title "Graph" in editor - you have built-in Grafana's Graph plugin running.

You should have separate "Multibar Graph Panel" in your plugins list, if you installed it correctly.
![image](https://user-images.githubusercontent.com/1989898/38089792-4c18a452-3369-11e8-99af-4905d466c4c7.png)

Can you, please, describe how you tried to build it step-by-step? Have you restarted your Grafana after cloning this repo?

P.S. As @jonyrock said - it's not necessary to build it. You can just clone repo in your *data/plugins* dir and restart Grafana. It should work that way.

**Comment by deepminimal** [comment]
@rozetko 
```
Hi!
cd /var/lib/grafana/plugins/
git clone https://github.com/CorpGlory/grafana-multibar-graph-panel
systemctl restart grafana-server 
```
1) Create new dashboard
2) add Multibar Panel 
![image](https://user-images.githubusercontent.com/18044597/38091163-5ca2ae22-336d-11e8-8470-1fb2ad306b9e.png)
3) Get metrics
![image](https://user-images.githubusercontent.com/18044597/38091444-436637fc-336e-11e8-8c2a-06776679314d.png)
4) Enable Side By Side
![image](https://user-images.githubusercontent.com/18044597/38091941-9a65b78e-336f-11e8-9f79-f16f5b6ab0ef.png)
5) Save Dashboard
6) Refresh ctrl + f5 and panel renamed "Graph"
![image](https://user-images.githubusercontent.com/18044597/38091999-c0872006-336f-11e8-8b5e-ed6e1d4e5acf.png)

**Comment by deepminimal** [comment]
@jonyrock What do you mean about "dist plugin"?

**Comment by rozetko** [comment]
@deepminimal oh, I see. There is a problem with the latest build. I'll let you know when I fix and test it. Thanks for feedback!

**Comment by deepminimal** [comment]
@rozetko Thank you very much! When will you support Grafana V5?

**Comment by rozetko** [comment]
@deepminimal actually, we support Grafana v5 and it is priority.

Can I ask you to follow steps from https://github.com/CorpGlory/grafana-multibar-graph-panel/issues/6#issuecomment-377238048 once again (including plugin remove and clone)? And clear your browser's cache (ctrl+shift+R) before creating dashboard (**it's important**).

**Comment by deepminimal** [comment]
@rozetko It seems that everything works! Thank you so much! Tested on Grafana v4.6.3 and v5.0.3!

**Comment by rozetko** [comment]
@deepminimal you're welcome! Thanks again for finding this bug! I can close this issue, I guess.

**Comment by jonyrock** [comment]
@deepminimal when I mentioned "dist plugin", I wanted to say somethin

```
cd $GRAFANA_PATH/data/plugins
git clone https://github.com/CorpGlory/grafana-multibar-graph-panel
systemctl restart grafana-server 
```

so you use the plugin without building it. The build conuld be done in your case something like:
```
cd $GRAFANA_PATH/data/plugins
git clone https://github.com/CorpGlory/grafana-multibar-graph-panel
cd grafana-multibar-graph-panel
npm install
npm run build // this will remove dist folder & make in with new build
systemctl restart grafana-server 
``
