### ISSUE TITLE
bar are not appear side by side in google chrome and firefox 

### ISSUE THREAD

**Issue by safirjava** [CorpGlory/grafana-multibar-graph-panel#8]
When i created side by side bar using this plugins, Its look good in safari browser, but it not appearing side by side in google chrome and firefox.

Attached screenshot   
<img width="1203" alt="google chrome" src="https://user-images.githubusercontent.com/4966989/39808171-dbc111fa-539b-11e8-819a-3c0398ab7670.png">

![safari](https://user-images.githubusercontent.com/4966989/39808183-e7495c80-539b-11e8-9983-6ba07e72af4e.png)

**Comment by jonyrock** [comment]
@safirjava strange cuz we tested it chrome and nowhere else. What version of Grafana are you using? 
Is there anything in Chrome debug console ?

**Comment by safirjava** [comment]
Sorry for late reply.
After clearing browser cache recreated the dashboard, its work. It was my mistake, created dashboard before installing this plugins. Later added the panel.

So process i followed which solved the issue as bellow
1. install the plugins in grafana
2. restart grafana. 
3. Clean up the browser cache .
4. Create new dashbord.

Closing the issue, Thanks for your help.

**Comment by jonyrock** [comment]
@safirjava oh, everybody has problems with grafana's cache
